server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pix_spring_microservices
    username: keycloak
    password: keycloak
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'